### ISSUE TITLE
What does the mlp and Mish function in modules.py do

### ISSUE THREAD

**Issue by Dyongh613** [keonlee9420/DiffGAN-TTS#4]
self.mlp = nn.Sequential(
            LinearNorm(residual_channels, residual_channels * 4),
            Mish(),                                                         # return x * torch.tanh(F.softplus(x))
            LinearNorm(residual_channels * 4, residual_channels)
        )

class Mish(nn.Module):
    def forward(self, x):
        return x * torch.tanh(F.softplus(x))

**Comment by keonlee9420** [comment]
Hi @qw1260497397 , it is for the embedding of diffusion time steps as described in the paper.

**Comment by keonlee9420** [comment]
Close due to inactivity.
