### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Dyongh613** [keonlee9420/DiffGAN-TTS#5]
raceback (most recent call last):                                                                                                                                                     | 0/5468 [00:00<?, ?it/s] 
  File "train.py", line 307, in <module>
    main(args, configs)
  File "train.py", line 99, in main
    output = model(*(batch[2:]))
TypeError: 'NoneType' object is not subscriptable

How can I solve this problem? Thank You!

**Comment by keonlee9420** [comment]
Hi @qw1260497397 , you have to match the number of elements in a batch [here](https://github.com/keonlee9420/DiffGAN-TTS/blob/bd312c3a0e7f02d3ce379aef11061f93105deb74/utils/tools.py#L37) to [this](https://github.com/keonlee9420/DiffGAN-TTS/blob/bd312c3a0e7f02d3ce379aef11061f93105deb74/dataset.py#L193).

**Comment by Dyongh613** [comment]
Thank you for your reply！ After adjust this problem, new problems have emerged.


&nbsp; File "train.py", line 306, in <module&gt;
&nbsp; &nbsp; main(args, configs)
&nbsp; File "train.py", line 98, in main
&nbsp; &nbsp; output, coarse_mels = model(*(batch[2:]))



&nbsp; &nbsp; result = self.forward(*input, **kwargs)
&nbsp; File "D:\workspace\LocalSpeech\model\diffgantts.py", line 82, in forward
&nbsp; &nbsp; if mel_lens is not None
&nbsp; File "D:\workspace\LocalSpeech\utils\tools.py", line 160, in get_mask_from_lengths
&nbsp; &nbsp; ids = torch.arange(0, max_len).unsqueeze(
TypeError: arange() received an invalid combination of arguments - got (int, Tensor), but expected one of:
&nbsp;* (Number end, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
&nbsp;* (Number start, Number end, Number step, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)



In ids = torch.arange(0, max_len).unsqueeze(...), If I remove 0, it shows that the input range needs to be an Number.
Thank You very much!



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "keonlee9420/DiffGAN-TTS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月21日(星期四) 上午10:52
***@***.***&gt;;
抄送:&nbsp;"Rui ***@***.******@***.***&gt;;
主题:&nbsp;Re: [keonlee9420/DiffGAN-TTS] TypeError: 'NoneType' object is not subscriptable (Issue #5)





 
Hi @qw1260497397 , you have to match the number of elements in a batch here to this.

**Comment by Dyongh613** [comment]
Thank you! I am trying to solve these problems now! Thank you very much!

**Comment by Dyongh613** [comment]
Hi @keonlee9420 , a new problem that I cannot deal with it.&nbsp;
1. Traceback (most recent call last):
&nbsp; File "train.py", line 306, in <module&gt;
&nbsp; &nbsp; main(args, configs)
&nbsp; File "train.py", line 98, in main
&nbsp; &nbsp; output, coarse_mels = model(*(batch[2:]))



&nbsp; &nbsp; if mel_lens is not None
&nbsp; File "D:\workspace\LocalSpeech\utils\tools.py", line 151, in get_mask_from_lengths
&nbsp; &nbsp; batch_size = lengths.shape[0]


IndexError: tuple index out of randge&nbsp; &nbsp; &nbsp;-- new problem&nbsp; &nbsp; &nbsp;I try to print the lengths.shape[0] that equals 8. In train.yaml , I set batch_size equals 8. And group_size equals 2



2. def get_mast from lenghts:
batch_size = lengths.shape[0]
if max_len is None:
    max_len = torch.max(lengths).item()

ids = torch.arange(0, max_len).unsqueeze(0).expand(batch_size, -1).to(device)
mask = ids &gt;= lengths.unsqueeze(1).expand(-1, max_len)

return mask
Thank you very much!&nbsp;
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "keonlee9420/DiffGAN-TTS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月21日(星期四) 上午10:52
***@***.***&gt;;
抄送:&nbsp;"Rui ***@***.******@***.***&gt;;
主题:&nbsp;Re: [keonlee9420/DiffGAN-TTS] TypeError: 'NoneType' object is not subscriptable (Issue #5)





 
Hi @qw1260497397 , you have to match the number of elements in a batch here to this.

**Comment by qw1260497397** [comment]
Hi 
[keonlee9420], I try to add some PortaSpeech modules into DiffGAN-TTS. In Portaspeech.py, mel_masks = (
  get_mask_from_lengths(mel_lens, max_mel_len). The tpye of mel_lens is tensor and max_mel_len is int. But, after copying into DiffGAN, the type of mel_lens changes into int while the max_mel_len becomes tensor.  I get the same method copying from Portaspeech all into DiffGAN. The problem cannot solved by me! Thank you!

**Comment by keonlee9420** [comment]
Please refer to the issue #6
