### ISSUE TITLE
About preprocess

### ISSUE THREAD

**Issue by CathyW77** [keonlee9420/DiffGAN-TTS#7]
HI, I wanna run "python3 preprocess.py --dataset VCTK"  after "python3 prepare_align.py --dataset VCTK", 
but in 
./preprocessor/preprocessor.py  
line :115     tg_path = os.path.join(self.out_dir, "TextGrid", speaker, "{}.TextGrid".format(basename)
I cannot find file named "*TextGrid", I want to know when it created?

After step  "python3 prepare_align.py --dataset VCTK" I only get files name ".lab" and ".wav", no files named ".TextGrid"

Thanks

**Comment by keonlee9420** [comment]
Hi @CathyW77 , thanks for your attention. You need to get textgrid beforehand preprocess.py by running MFA as described in README.md.

**Comment by keonlee9420** [comment]
Closed due to inactivity.
